package com.alibaba.android.arouter.register.utils
/**
 * register setting
 * @author billy.qi email: qiyilike@163.com
 * @since 17/3/28 11:48
 */
class ScanSetting {
    //插件名字
    static final String PLUGIN_NAME = "com.alibaba.arouter"
    /**
     * The register code is generated into this class
     * 注册码生成到这个类中
     */
    static final String GENERATE_TO_CLASS_NAME = 'com/alibaba/android/arouter/core/LogisticsCenter'
    /**
     * you know. this is the class file(or entry in jar file) name
     * 你知道。这是类文件（或 jar 文件中的条目）名称
     * LogisticsCenter字节码文件的全路径
     */
    static final String GENERATE_TO_CLASS_FILE_NAME = GENERATE_TO_CLASS_NAME + '.class'
    /**
     * The register code is generated into this method in class: {@link #GENERATE_TO_CLASS_NAME}
     * LogisticsCenter类中注册代码码生成到这个方法中
     */
    static final String GENERATE_TO_METHOD_NAME = 'loadRouterMap'
    /**
     * The package name of the class generated by the annotationProcessor
     * annotationProcessor 生成的类的包名的路径 com/alibaba/android/arouter/routes/
     */
    static final String ROUTER_CLASS_PACKAGE_NAME = 'com/alibaba/android/arouter/routes/'
    /**
     * The package name of the interfaces
     * annotationProcessor 生成的类实现接口的包名的路径
     */
    private static final INTERFACE_PACKAGE_NAME = 'com/alibaba/android/arouter/facade/template/'

    /**
     * register method name in class: {@link #GENERATE_TO_CLASS_NAME}
     * 在LogisticsCenter类中注册方法名称
     */
    static final String REGISTER_METHOD_NAME = 'register'

    /**
     * scan for classes which implements this interface
     * 扫描实现此接口的类
     * com/alibaba/android/arouter/facade/template/IRouteRoot
     */
    String interfaceName = ''

    /**
     * jar file which contains class: {@link #GENERATE_TO_CLASS_NAME}
     */
    File fileContainsInitClass

    /**
     * scan result for {@link #interfaceName}
     * class names in this list
     * 扫描结果
     */
    ArrayList<String> classList = new ArrayList<>()

    /**
     * constructor for arouter-auto-register settings
     * @param interfaceName interface to scan
     */
    ScanSetting(String interfaceName){
        this.interfaceName = INTERFACE_PACKAGE_NAME + interfaceName
    }

}